---
parser: babel-eslint

extends: eslint-config-shakacode

plugins:
  - react

globals:
  __DEBUG_SERVER_ERRORS__: true
  __SERVER_ERRORS__: true

env:
  browser: true
  node: true
  mocha: true

rules:
  ### Variables
  no-undef: 2
  no-unused-vars: [2, { vars: all, args: none }]

  ### Stylistic issues
  indent: [1, 2, { SwitchCase: 1, VariableDeclarator: 2 }]
  id-length: [1, { min: 2, exceptions: [_, e, i, k, v] }]
  space-before-function-paren: [1, "never"]
  no-underscore-dangle: 0

  ### Imports
  # Can't do next one because of alias in webpack
  import/no-unresolved: 0
  import/extensions: [2, { js: "never", jsx: "never" }]

  # https://github.com/benmosher/eslint-plugin-import/issues/340
  import/no-extraneous-dependencies: 0

  # https://github.com/eslint/eslint/issues/6876 SFC's marked as invalid
  new-cap: 0

  ### React
  jsx-quotes: [1, prefer-double]
  react/display-name: 0
  react/jsx-boolean-value: [1, always]
  react/jsx-curly-spacing: [1, never]
  react/jsx-no-duplicate-props: [2, { ignoreCase: true }]
  react/jsx-no-undef: 2
  react/jsx-sort-prop-types: 0
  react/jsx-sort-props: 0
  react/jsx-uses-react: 2
  react/jsx-uses-vars: 2
  react/no-danger: 0
  react/no-did-mount-set-state: 1
  react/no-did-update-set-state: 0
  react/no-multi-comp: 2
  react/no-unknown-property: 2
  react/prop-types: 1
  react/react-in-jsx-scope: 2
  react/self-closing-comp: 2
  react/sort-comp: 0                                                            # Should be 1. `statics` should be on top.
  react/jsx-wrap-multilines: 2
