***REMOVED***
  adapter: async

***REMOVED***
  adapter: async

***REMOVED***
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
  channel_prefix: rails_react_tutorial_production
