***REMOVED***

***REMOVED***
***REMOVED***

***REMOVED***
***REMOVED***
# You can use `rake secret` to generate a secure secret key.

***REMOVED***
***REMOVED***

***REMOVED***
  secret_key_base: 231bf79489c63f8c8facd7bf27db1c2582a42a7f4302fccdb74ef35bc5dc91fb4e19dbf167f3003bdb4073818dfab4a9916890d193d535a7be458dbef1609800

***REMOVED***
  secret_key_base: 1ab8adbcf8410aebbce9b6dd6db7b5d090297bd22cf789b91ff44ae02711e8c128453d3e5c97eadf9066efe1a1e0dc1921faf7314d566c114d3ed60ae7ea614c

# Do not keep production secrets in the repository,
# instead read values from the environment.
***REMOVED***
***REMOVED***
